apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ao9clexdp-nodejs
  janus-idp.io/tekton: ao9clexdp-nodejs
  backstage.io/kubernetes-id: ao9clexdp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ao9clexdp-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
