apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ao9clexdp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ao9clexdp-nodejs 
  name: ao9clexdp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ao9clexdp-nodejs 
